export type ProjectPath =
  | "PREDICTION_MARKET"
  | "FREELANCE_ESCROW"
  | "DAO"
  | "DEVELOPER_REPUTATION"
  | "INSURANCE";

export const CAPSTONE_NAMES: Record<ProjectPath, string> = {
  PREDICTION_MARKET:    "PredictX",
  FREELANCE_ESCROW:     "TrustLance",
  DAO:                  "GovMind",
  DEVELOPER_REPUTATION: "CodeVault",
  INSURANCE:            "CaseWise",
};

export const CAPSTONE_TAGLINES: Record<ProjectPath, string> = {
  PREDICTION_MARKET:    "AI-Resolved Prediction Market",
  FREELANCE_ESCROW:     "Freelance Escrow Platform",
  DAO:                  "AI-Governed DAO",
  DEVELOPER_REPUTATION: "Private Code Marketplace",
  INSURANCE:            "AI-Assisted Dispute Resolution",
};

export interface LessonMeta {
  id: number;
  groupId: number;
  isCapstone: boolean;
  concept: string;
  docUrl: string;
  titles: Record<ProjectPath, string>;
  shortDescriptions: Record<ProjectPath, string>;
}

export const LESSONS: LessonMeta[] = [
  { id:1,groupId:1,isCapstone:false,concept:"Platform overview & GenLayer fundamentals",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"What You Are Building: AI-Resolved Markets",FREELANCE_ESCROW:"What You Are Building: Freelance Escrow",DAO:"What You Are Building: AI-Governed DAO",DEVELOPER_REPUTATION:"What You Are Building: Private Code Marketplace",INSURANCE:"What You Are Building: AI Dispute Court"},shortDescriptions:{PREDICTION_MARKET:"Understand PredictX and why GenLayer resolves real-world outcomes better than oracles.",FREELANCE_ESCROW:"Understand TrustLance and how intelligent contracts protect clients and freelancers.",DAO:"Understand GovMind and where AI adds real value to on-chain governance.",DEVELOPER_REPUTATION:"Understand CodeVault and how a private code marketplace needs escrow and privacy.",INSURANCE:"Understand CaseWise and how AI can assist arbitration at scale."}},
  { id:2,groupId:1,isCapstone:false,concept:"gl.Contract skeleton & constructor",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"PredictX Contract Skeleton",FREELANCE_ESCROW:"TrustLance Contract Skeleton",DAO:"GovMind Contract Skeleton",DEVELOPER_REPUTATION:"CodeVault Contract Skeleton",INSURANCE:"CaseWise Contract Skeleton"},shortDescriptions:{PREDICTION_MARKET:"Write the PredictX class with GenLayer header, imports, owner field, and constructor.",FREELANCE_ESCROW:"Write the TrustLance class with header, imports, owner field, and constructor.",DAO:"Write the GovMind class with header, imports, owner, and constructor.",DEVELOPER_REPUTATION:"Write the CodeVault class with header, imports, owner, and constructor.",INSURANCE:"Write the CaseWise class with header, imports, owner, and constructor."}},
  { id:3,groupId:1,isCapstone:false,concept:"@gl.public.view",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features",titles:{PREDICTION_MARKET:"Reading Market Metadata",FREELANCE_ESCROW:"Reading Platform Info",DAO:"DAO Info View",DEVELOPER_REPUTATION:"Marketplace Info View",INSURANCE:"Court Info View"},shortDescriptions:{PREDICTION_MARKET:"Expose platform name and owner with @gl.public.view — gas-free reads for the frontend.",FREELANCE_ESCROW:"Return platform info with @gl.public.view — read-only, no transaction required.",DAO:"Return DAO metadata with @gl.public.view — read-only methods cost no gas.",DEVELOPER_REPUTATION:"Return marketplace info with @gl.public.view — safe gas-free reads.",INSURANCE:"Return court metadata with @gl.public.view — the first readable contract."}},
  { id:4,groupId:1,isCapstone:false,concept:"@gl.public.write",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features",titles:{PREDICTION_MARKET:"Updating Platform Settings",FREELANCE_ESCROW:"Updating Platform Info",DAO:"Updating DAO Description",DEVELOPER_REPUTATION:"Updating Marketplace Settings",INSURANCE:"Updating Court Settings"},shortDescriptions:{PREDICTION_MARKET:"Add @gl.public.write to update the platform name — your first state-mutating transaction.",FREELANCE_ESCROW:"Add @gl.public.write to update platform description — understand write transactions.",DAO:"Add @gl.public.write to update DAO description — state mutations need a signed tx.",DEVELOPER_REPUTATION:"Add @gl.public.write to update the marketplace name — your first write transaction.",INSURANCE:"Add @gl.public.write to update court settings — consensus-validated state changes."}},
  { id:5,groupId:1,isCapstone:true,concept:"Identity contract (Group 1 capstone)",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Major Upgrade — Prediction Market Identity Contract",FREELANCE_ESCROW:"Major Upgrade — Freelance Platform Identity",DAO:"Major Upgrade — DAO Identity Contract",DEVELOPER_REPUTATION:"Major Upgrade — Marketplace Identity Contract",INSURANCE:"Major Upgrade — Arbitration Platform Identity"},shortDescriptions:{PREDICTION_MARKET:"Combine owner, constructor, view, and write into a clean PredictX identity contract.",FREELANCE_ESCROW:"Combine constructor, persistent fields, and methods into a complete TrustLance identity.",DAO:"Combine owner, metadata, view, and write into a polished GovMind identity contract.",DEVELOPER_REPUTATION:"Ship the CodeVault identity contract — a clean base ready for listing storage.",INSURANCE:"Ship the CaseWise identity contract — owner, metadata, views, and writes all working."}},
  { id:6,groupId:2,isCapstone:false,concept:"Persistent storage fields",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Market Storage Fields",FREELANCE_ESCROW:"Job Storage Fields",DAO:"Member Storage",DEVELOPER_REPUTATION:"Listing Storage Fields",INSURANCE:"Case Storage Fields"},shortDescriptions:{PREDICTION_MARKET:"Declare market_count and name/description fields as persistent class-level state.",FREELANCE_ESCROW:"Declare job_count and title/description fields as persistent class-level state.",DAO:"Declare a members TreeMap and member_count as persistent class-level storage.",DEVELOPER_REPUTATION:"Declare listing_count and title/description fields as persistent class-level state.",INSURANCE:"Declare case_count and claimant/respondent fields as persistent class-level state."}},
  { id:7,groupId:2,isCapstone:false,concept:"Address & gl.message.sender_address",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/transaction-context",titles:{PREDICTION_MARKET:"Tracking Market Creators",FREELANCE_ESCROW:"Client Address Tracking",DAO:"Adding Members",DEVELOPER_REPUTATION:"Seller Address Tracking",INSURANCE:"Party Address Tracking"},shortDescriptions:{PREDICTION_MARKET:"Store the creator's wallet address using gl.message.sender_address.",FREELANCE_ESCROW:"Capture the client's wallet address when a job is created.",DAO:"Add member addresses with the Address type and gl.message.sender_address.",DEVELOPER_REPUTATION:"Capture the seller's wallet address on listing creation.",INSURANCE:"Store claimant and respondent addresses using Address and sender_address."}},
  { id:8,groupId:2,isCapstone:false,concept:"u256 numeric storage",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types",titles:{PREDICTION_MARKET:"Market Fees and Stakes",FREELANCE_ESCROW:"Job Budgets with u256",DAO:"Voting Power with u256",DEVELOPER_REPUTATION:"Listing Price with u256",INSURANCE:"Case Fees with u256"},shortDescriptions:{PREDICTION_MARKET:"Store minimum stake as u256 — the fixed-width integer type for all on-chain amounts.",FREELANCE_ESCROW:"Store job budget as u256 — always use fixed-width integers for payment amounts.",DAO:"Store per-member voting weight as u256 for weighted governance.",DEVELOPER_REPUTATION:"Store listing price as u256 — the correct type for all on-chain monetary values.",INSURANCE:"Store the review fee bond as u256 — required deposit before a case can proceed."}},
  { id:9,groupId:2,isCapstone:false,concept:"TreeMap[str, T]",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Market Records with TreeMap",FREELANCE_ESCROW:"Job Records with TreeMap",DAO:"Proposal Storage with TreeMap",DEVELOPER_REPUTATION:"Private Source Metadata",INSURANCE:"Case Records with TreeMap"},shortDescriptions:{PREDICTION_MARKET:"Use TreeMap to store multiple market records by ID — on-chain key-value persistence.",FREELANCE_ESCROW:"Use TreeMap to store many job records by ID — the backbone of multi-record contracts.",DAO:"Use TreeMap to store proposal records by ID — ordered on-chain storage.",DEVELOPER_REPUTATION:"Store source hash and IPFS CID in a TreeMap — keeping private data off-chain.",INSURANCE:"Use TreeMap to store multiple case records by ID — ordered on-chain persistence."}},
  { id:10,groupId:2,isCapstone:true,concept:"Record creation (Group 2 capstone)",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Major Upgrade — Create a Prediction Market",FREELANCE_ESCROW:"Major Upgrade — Create Jobs",DAO:"Major Upgrade — Create Proposals",DEVELOPER_REPUTATION:"Major Upgrade — Create Code Listings",INSURANCE:"Major Upgrade — Submit Cases"},shortDescriptions:{PREDICTION_MARKET:"Build create_market() with full input validation and TreeMap record creation.",FREELANCE_ESCROW:"Build create_job() with input validation, address capture, and TreeMap storage.",DAO:"Build create_proposal() with member-only access and TreeMap record creation.",DEVELOPER_REPUTATION:"Build create_listing() with price, source hash, and preview metadata.",INSURANCE:"Build submit_case() with party addresses and full TreeMap record creation."}},
  { id:11,groupId:3,isCapstone:false,concept:"DynArray",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Indexing Markets with DynArray",FREELANCE_ESCROW:"Job Indexing with DynArray",DAO:"Proposal Indexing",DEVELOPER_REPUTATION:"Listing Indexing with DynArray",INSURANCE:"Case Indexing with DynArray"},shortDescriptions:{PREDICTION_MARKET:"Add a market_ids DynArray to track all created markets in insertion order.",FREELANCE_ESCROW:"Add a job_ids DynArray to index all created jobs for browsing.",DAO:"Add a proposal_ids DynArray so the frontend can enumerate all proposals.",DEVELOPER_REPUTATION:"Add a listing_ids DynArray to index all listings for the marketplace.",INSURANCE:"Add a case_ids DynArray to index all submitted cases for the dashboard."}},
  { id:12,groupId:3,isCapstone:false,concept:"json.dumps views",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features",titles:{PREDICTION_MARKET:"Market JSON View",FREELANCE_ESCROW:"Job JSON View",DAO:"Proposal JSON View",DEVELOPER_REPUTATION:"Listing JSON View",INSURANCE:"Case JSON View"},shortDescriptions:{PREDICTION_MARKET:"Build get_market_json() returning a JSON string — the standard frontend data format.",FREELANCE_ESCROW:"Build get_job_json() returning a JSON string for frontend job display.",DAO:"Build get_proposal_json() returning a JSON string for the governance UI.",DEVELOPER_REPUTATION:"Build get_listing_json() returning safe public listing data as JSON.",INSURANCE:"Build get_case_json() returning a JSON string for the arbitration dashboard."}},
  { id:13,groupId:3,isCapstone:false,concept:"Index + filter loops",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Listing Active Markets",FREELANCE_ESCROW:"Listing Open Jobs",DAO:"Listing Open Proposals",DEVELOPER_REPUTATION:"Active Listings View",INSURANCE:"Listing Open Cases"},shortDescriptions:{PREDICTION_MARKET:"Build get_active_markets_json() by looping market_ids and filtering by status.",FREELANCE_ESCROW:"Build get_open_jobs_json() by looping job_ids and filtering for OPEN status.",DAO:"Build get_open_proposals_json() to enumerate and filter active proposals.",DEVELOPER_REPUTATION:"Build get_all_listings_json() filtering ACTIVE status via DynArray iteration.",INSURANCE:"Build get_open_cases_json() to enumerate and filter submitted cases."}},
  { id:14,groupId:3,isCapstone:false,concept:"Status state machines",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Market Status Flow",FREELANCE_ESCROW:"Job Status Flow",DAO:"Proposal Status Flow",DEVELOPER_REPUTATION:"Listing Status Flow",INSURANCE:"Case Status Flow"},shortDescriptions:{PREDICTION_MARKET:"Model ACTIVE → CLOSED → RESOLVED → CLAIMED for prediction markets.",FREELANCE_ESCROW:"Model OPEN → FUNDED → ACCEPTED → DELIVERED → RELEASED/REFUNDED/DISPUTED.",DAO:"Model OPEN → PASSED/REJECTED → EXECUTED/CANCELLED for proposals.",DEVELOPER_REPUTATION:"Model ACTIVE → PENDING → SOLD/REFUNDED/REMOVED for listings.",INSURANCE:"Model SUBMITTED → REVIEWING → RULED → APPEALED/CLOSED for cases."}},
  { id:15,groupId:3,isCapstone:true,concept:"Dashboard-ready contract (Group 3 capstone)",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Major Upgrade — Browseable Market Dashboard Contract",FREELANCE_ESCROW:"Major Upgrade — Browseable Freelance Marketplace",DAO:"Major Upgrade — Browseable DAO Governance Board",DEVELOPER_REPUTATION:"Major Upgrade — Browseable Code Marketplace",INSURANCE:"Major Upgrade — Browseable Case Dashboard"},shortDescriptions:{PREDICTION_MARKET:"Combine indexing, JSON views, status filtering — PredictX can power a frontend.",FREELANCE_ESCROW:"Combine job listing, JSON views, and status filtering into a full marketplace.",DAO:"Ship a governance contract with proposal indexing, JSON views, and status filtering.",DEVELOPER_REPUTATION:"Combine listing indexing, JSON views, and status filtering into a complete marketplace.",INSURANCE:"Ship a case dashboard contract with indexing, JSON views, and status filtering."}},
  { id:16,groupId:4,isCapstone:false,concept:"@gl.public.write.payable",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/balances",titles:{PREDICTION_MARKET:"Payable Staking",FREELANCE_ESCROW:"Funding a Job",DAO:"Voting Method",DEVELOPER_REPUTATION:"Buying a Listing",INSURANCE:"Paying Review Fees"},shortDescriptions:{PREDICTION_MARKET:"Add stake_on_outcome() with @gl.public.write.payable — accept GEN via gl.message.value.",FREELANCE_ESCROW:"Add fund_job() with @gl.public.write.payable to lock GEN into escrow.",DAO:"Add vote() so members can cast yes/no votes on proposals.",DEVELOPER_REPUTATION:"Add buy() with @gl.public.write.payable to lock the listing price in escrow.",INSURANCE:"Add pay_case_fee() with @gl.public.write.payable to lock the review bond."}},
  { id:17,groupId:4,isCapstone:false,concept:"Input validation & gl.vm.UserError",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/error-handling",titles:{PREDICTION_MARKET:"Preventing Bad Stakes",FREELANCE_ESCROW:"Accepting a Job",DAO:"Preventing Duplicate Votes",DEVELOPER_REPUTATION:"Buyer and Seller Rules",INSURANCE:"Adding Evidence"},shortDescriptions:{PREDICTION_MARKET:"Reject invalid outcomes, closed markets, and zero stakes with gl.vm.UserError.",FREELANCE_ESCROW:"Add accept_job() — only a freelancer can accept a funded job.",DAO:"Track has_voted per member to prevent duplicate votes with a TreeMap guard.",DEVELOPER_REPUTATION:"Prevent sellers from buying their own listings with explicit caller checks.",INSURANCE:"Add add_evidence() with authorization guards — only parties can submit evidence."}},
  { id:18,groupId:4,isCapstone:false,concept:"User-keyed TreeMap storage",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/types/collections",titles:{PREDICTION_MARKET:"Tracking User Stakes",FREELANCE_ESCROW:"Delivery Submission",DAO:"Counting Votes",DEVELOPER_REPUTATION:"Escrow Storage",INSURANCE:"Evidence and Party Rules"},shortDescriptions:{PREDICTION_MARKET:"Track stakes per user per market using a composite TreeMap key.",FREELANCE_ESCROW:"Add submit_delivery() for freelancers to record a work reference for client review.",DAO:"Track for_votes and against_votes as u256 counters to tally governance outcomes.",DEVELOPER_REPUTATION:"Store buyer address, escrow amount, and status in a purchase-keyed TreeMap.",INSURANCE:"Store per-party evidence refs with authorization — only parties may add evidence."}},
  { id:19,groupId:4,isCapstone:false,concept:"Release & refund patterns",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/value-transfers",titles:{PREDICTION_MARKET:"Claim and Refund Patterns",FREELANCE_ESCROW:"Release and Refund",DAO:"Proposal Execution",DEVELOPER_REPUTATION:"Confirm and Refund Purchase",INSURANCE:"Ruling and Refund Patterns"},shortDescriptions:{PREDICTION_MARKET:"Build claim_winnings() — funds release only after resolution, blocked otherwise.",FREELANCE_ESCROW:"Build confirm_delivery() and refund_job() to release or return locked escrow.",DAO:"Build execute_proposal() — status-gated execution for approved proposals only.",DEVELOPER_REPUTATION:"Build confirm_purchase() and refund() — sellers receive payment on confirmation.",INSURANCE:"Build close_case() and refund_case_fee() — ruling triggers the fee release."}},
  { id:20,groupId:4,isCapstone:true,concept:"Full value flow (Group 4 capstone)",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/balances",titles:{PREDICTION_MARKET:"Major Upgrade — Full Prediction Value Flow",FREELANCE_ESCROW:"Major Upgrade — Complete Freelance Escrow Flow",DAO:"Major Upgrade — Full Governance Voting Flow",DEVELOPER_REPUTATION:"Major Upgrade — Full Code Purchase Escrow",INSURANCE:"Major Upgrade — Paid Dispute Flow"},shortDescriptions:{PREDICTION_MARKET:"Combine payable staking, locked escrow, and claim state — PredictX handles real value.",FREELANCE_ESCROW:"Ship the full fund → accept → deliver → release/refund TrustLance escrow system.",DAO:"Ship full governance: vote, tally, pass/reject, and execute proposals on-chain.",DEVELOPER_REPUTATION:"Ship the full buy → confirm/refund CodeVault escrow — a real purchase system.",INSURANCE:"Ship the full case fees → evidence → ruling → release CaseWise flow."}},
  { id:21,groupId:5,isCapstone:false,concept:"AI reasoning concepts",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/calling-llms",titles:{PREDICTION_MARKET:"AI Resolution Basics",FREELANCE_ESCROW:"AI Dispute Review Basics",DAO:"AI Proposal Summary",DEVELOPER_REPUTATION:"AI Code Preview Review",INSURANCE:"AI Evidence Review Basics"},shortDescriptions:{PREDICTION_MARKET:"Understand why outcome resolution needs AI — and design your resolution prompt.",FREELANCE_ESCROW:"Understand how AI compares a job description against a delivery reference.",DAO:"Understand how AI summarizes proposal risks for governance decisions.",DEVELOPER_REPUTATION:"Understand how AI evaluates a code preview against seller claims.",INSURANCE:"Understand how AI compares claims against evidence to assist arbitration."}},
  { id:22,groupId:5,isCapstone:false,concept:"gl.nondet.exec_prompt",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/calling-llms",titles:{PREDICTION_MARKET:"Using gl.nondet.exec_prompt",FREELANCE_ESCROW:"Delivery Review with gl.nondet.exec_prompt",DAO:"Using gl.nondet.exec_prompt for Proposals",DEVELOPER_REPUTATION:"Using gl.nondet.exec_prompt for Code Review",INSURANCE:"Using gl.nondet.exec_prompt for Evidence"},shortDescriptions:{PREDICTION_MARKET:"Call gl.nondet.exec_prompt to ask the AI whether a market outcome has occurred.",FREELANCE_ESCROW:"Call gl.nondet.exec_prompt to ask the AI if a delivery satisfies the job.",DAO:"Call gl.nondet.exec_prompt to generate a risk summary for a proposal.",DEVELOPER_REPUTATION:"Call gl.nondet.exec_prompt to evaluate a code listing preview.",INSURANCE:"Call gl.nondet.exec_prompt to review case evidence and suggest a ruling."}},
  { id:23,groupId:5,isCapstone:false,concept:"run_nondet_unsafe validation",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/non-determinism",titles:{PREDICTION_MARKET:"AI Result Validation",FREELANCE_ESCROW:"AI Dispute Validation",DAO:"Validation for AI Governance",DEVELOPER_REPUTATION:"AI Listing Validation",INSURANCE:"Validation for Rulings"},shortDescriptions:{PREDICTION_MARKET:"Validate leader AI output with gl.vm.run_nondet_unsafe so validators can check the result shape.",FREELANCE_ESCROW:"Validate AI dispute output with explicit validator criteria for safe consensus.",DAO:"Apply validator checks to keep AI proposal analysis structured.",DEVELOPER_REPUTATION:"Validate AI listing verdicts with explicit output-shape checks.",INSURANCE:"Validate AI ruling outputs before storing them on-chain."}},
  { id:24,groupId:5,isCapstone:false,concept:"Structured AI JSON output",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/calling-llms",titles:{PREDICTION_MARKET:"Structured Resolution Output",FREELANCE_ESCROW:"Structured Dispute Output",DAO:"Structured AI Governance Output",DEVELOPER_REPUTATION:"Structured AI Listing Verdict",INSURANCE:"Structured Ruling Output"},shortDescriptions:{PREDICTION_MARKET:"Ask the AI for JSON: winning_outcome, confidence, explanation — parse and store it.",FREELANCE_ESCROW:"Ask the AI for verdict, confidence, reason, suggested_action as structured JSON.",DAO:"Get summary, risk_score, recommendation, caveats from AI as a JSON object.",DEVELOPER_REPUTATION:"Get verdict, confidence, explanation, caveats from AI — return as JSON.",INSURANCE:"Get verdict, confidence, reasoning, recommended_remedy from AI as JSON."}},
  { id:25,groupId:5,isCapstone:true,concept:"AI-powered contract (Group 5 capstone)",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/calling-llms",titles:{PREDICTION_MARKET:"Major Upgrade — AI Market Resolver",FREELANCE_ESCROW:"Major Upgrade — AI-Assisted Dispute Engine",DAO:"Major Upgrade — AI Proposal Analyst",DEVELOPER_REPUTATION:"Major Upgrade — AI Listing Judge",INSURANCE:"Major Upgrade — AI Arbitration Engine"},shortDescriptions:{PREDICTION_MARKET:"Ship resolve_market_with_ai() — PredictX becomes a true Intelligent Contract.",FREELANCE_ESCROW:"Ship review_dispute_with_ai() — TrustLance resolves disputes without humans.",DAO:"Ship analyze_proposal_with_ai() — GovMind provides AI-assisted governance review.",DEVELOPER_REPUTATION:"Ship evaluate_listing_with_ai() — CodeVault has an intelligent listing judge.",INSURANCE:"Ship review_case_with_ai() — CaseWise becomes an AI-powered arbitration engine."}},
  { id:26,groupId:6,isCapstone:false,concept:"Security hardening & gl.vm.UserError",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features/error-handling",titles:{PREDICTION_MARKET:"Prediction Market Security Mistakes",FREELANCE_ESCROW:"Escrow Safety Mistakes",DAO:"DAO Safety Mistakes",DEVELOPER_REPUTATION:"Source Reveal Security",INSURANCE:"Dispute System Safety Mistakes"},shortDescriptions:{PREDICTION_MARKET:"Guard against early claims, invalid outcomes, and duplicate claims.",FREELANCE_ESCROW:"Prevent early release, wrong caller access, and duplicate refunds.",DAO:"Guard against non-member votes, duplicate votes, and early execution.",DEVELOPER_REPUTATION:"Never unlock source from un-released escrow — define the released-only rule.",INSURANCE:"Prevent one-sided evidence, early rulings, and invalid party access."}},
  { id:27,groupId:6,isCapstone:false,concept:"Frontend integration patterns",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/features",titles:{PREDICTION_MARKET:"Frontend Integration for Markets",FREELANCE_ESCROW:"Frontend Flow for Freelance Escrow",DAO:"Frontend Integration for DAO",DEVELOPER_REPUTATION:"Seller Reputation",INSURANCE:"Appeal Logic"},shortDescriptions:{PREDICTION_MARKET:"Map create, list, stake, resolve, and claim contract methods to frontend actions.",FREELANCE_ESCROW:"Map create, fund, accept, deliver, confirm, and dispute to UI screens.",DAO:"Map membership, proposal, voting, analysis, and execution to UI actions.",DEVELOPER_REPUTATION:"Add vote_seller() and reputation views so buyers can signal trust after purchases.",INSURANCE:"Add appeal_case() with appeal fee — advanced dispute flow for contested rulings."}},
  { id:28,groupId:6,isCapstone:false,concept:"End-to-end testing",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Testing the Market Flow",FREELANCE_ESCROW:"Testing TrustLance",DAO:"Testing GovMind",DEVELOPER_REPUTATION:"Testing CodeVault",INSURANCE:"Testing CaseWise"},shortDescriptions:{PREDICTION_MARKET:"Walk through create → stake → resolve → claim and verify each step.",FREELANCE_ESCROW:"Walk through create → fund → accept → deliver → confirm.",DAO:"Walk through add member → create proposal → vote → analyze → execute.",DEVELOPER_REPUTATION:"Walk through create → buy → confirm → vote to validate the full flow.",INSURANCE:"Walk through submit → pay fee → add evidence → review → rule → appeal."}},
  { id:29,groupId:6,isCapstone:false,concept:"Capstone assembly",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Capstone Assembly",FREELANCE_ESCROW:"Capstone Assembly",DAO:"Capstone Assembly",DEVELOPER_REPUTATION:"Capstone Assembly",INSURANCE:"Capstone Assembly"},shortDescriptions:{PREDICTION_MARKET:"Assemble all PredictX components: storage, reads, staking, AI resolution, and claims.",FREELANCE_ESCROW:"Assemble all TrustLance components: job storage, escrow, delivery, AI dispute.",DAO:"Assemble all GovMind components: membership, voting, AI analysis, and execution.",DEVELOPER_REPUTATION:"Assemble all CodeVault components: listings, escrow, AI review, and reputation.",INSURANCE:"Assemble all CaseWise components: cases, evidence, fees, AI ruling, and appeals."}},
  { id:30,groupId:6,isCapstone:true,concept:"Final capstone deploy",docUrl:"https://docs.genlayer.com/developers/intelligent-contracts/introduction",titles:{PREDICTION_MARKET:"Final Capstone — Ship PredictX",FREELANCE_ESCROW:"Final Capstone — Ship TrustLance",DAO:"Final Capstone — Ship GovMind",DEVELOPER_REPUTATION:"Final Capstone — Ship CodeVault",INSURANCE:"Final Capstone — Ship CaseWise"},shortDescriptions:{PREDICTION_MARKET:"Deploy and verify the complete PredictX AI-resolved prediction market.",FREELANCE_ESCROW:"Deploy and verify the complete TrustLance freelance escrow platform.",DAO:"Deploy and verify the complete GovMind AI-governed DAO.",DEVELOPER_REPUTATION:"Deploy and verify the complete CodeVault private code marketplace.",INSURANCE:"Deploy and verify the complete CaseWise AI-assisted dispute resolution system."}},
];

export function getLesson(id: number): LessonMeta | undefined {
  return LESSONS.find((l) => l.id === id);
}

export function getLessonsInGroup(groupId: number): LessonMeta[] {
  return LESSONS.filter((l) => l.groupId === groupId);
}

export function isLessonUnlocked(lessonId: number, completedIds: number[]): boolean {
  if (lessonId === 1) return true;
  return completedIds.includes(lessonId - 1);
}
