import type { LessonContent } from "@/types/content";

type ProjectPath =
  | "PREDICTION_MARKET"
  | "FREELANCE_ESCROW"
  | "DAO"
  | "DEVELOPER_REPUTATION"
  | "INSURANCE";

const contentMap: Record<string, () => Promise<{ default: LessonContent }>> = {
  "01-PREDICTION_MARKET": () => import("./lesson-01-PREDICTION_MARKET"),
  "01-FREELANCE_ESCROW": () => import("./lesson-01-FREELANCE_ESCROW"),
  "01-DAO": () => import("./lesson-01-DAO"),
  "01-DEVELOPER_REPUTATION": () => import("./lesson-01-DEVELOPER_REPUTATION"),
  "01-INSURANCE": () => import("./lesson-01-INSURANCE"),
  "02-PREDICTION_MARKET": () => import("./lesson-02-PREDICTION_MARKET"),
  "02-FREELANCE_ESCROW": () => import("./lesson-02-FREELANCE_ESCROW"),
  "02-DAO": () => import("./lesson-02-DAO"),
  "02-DEVELOPER_REPUTATION": () => import("./lesson-02-DEVELOPER_REPUTATION"),
  "02-INSURANCE": () => import("./lesson-02-INSURANCE"),
  "03-PREDICTION_MARKET": () => import("./lesson-03-PREDICTION_MARKET"),
  "03-FREELANCE_ESCROW": () => import("./lesson-03-FREELANCE_ESCROW"),
  "03-DAO": () => import("./lesson-03-DAO"),
  "03-DEVELOPER_REPUTATION": () => import("./lesson-03-DEVELOPER_REPUTATION"),
  "03-INSURANCE": () => import("./lesson-03-INSURANCE"),
  "04-PREDICTION_MARKET": () => import("./lesson-04-PREDICTION_MARKET"),
  "04-FREELANCE_ESCROW": () => import("./lesson-04-FREELANCE_ESCROW"),
  "04-DAO": () => import("./lesson-04-DAO"),
  "04-DEVELOPER_REPUTATION": () => import("./lesson-04-DEVELOPER_REPUTATION"),
  "04-INSURANCE": () => import("./lesson-04-INSURANCE"),
  "05-PREDICTION_MARKET": () => import("./lesson-05-PREDICTION_MARKET"),
  "05-FREELANCE_ESCROW": () => import("./lesson-05-FREELANCE_ESCROW"),
  "05-DAO": () => import("./lesson-05-DAO"),
  "05-DEVELOPER_REPUTATION": () => import("./lesson-05-DEVELOPER_REPUTATION"),
  "05-INSURANCE": () => import("./lesson-05-INSURANCE"),
  "06-PREDICTION_MARKET": () => import("./lesson-06-PREDICTION_MARKET"),
  "06-FREELANCE_ESCROW": () => import("./lesson-06-FREELANCE_ESCROW"),
  "06-DAO": () => import("./lesson-06-DAO"),
  "06-DEVELOPER_REPUTATION": () => import("./lesson-06-DEVELOPER_REPUTATION"),
  "06-INSURANCE": () => import("./lesson-06-INSURANCE"),
  "07-PREDICTION_MARKET": () => import("./lesson-07-PREDICTION_MARKET"),
  "07-FREELANCE_ESCROW": () => import("./lesson-07-FREELANCE_ESCROW"),
  "07-DAO": () => import("./lesson-07-DAO"),
  "07-DEVELOPER_REPUTATION": () => import("./lesson-07-DEVELOPER_REPUTATION"),
  "07-INSURANCE": () => import("./lesson-07-INSURANCE"),
  "08-PREDICTION_MARKET": () => import("./lesson-08-PREDICTION_MARKET"),
  "08-FREELANCE_ESCROW": () => import("./lesson-08-FREELANCE_ESCROW"),
  "08-DAO": () => import("./lesson-08-DAO"),
  "08-DEVELOPER_REPUTATION": () => import("./lesson-08-DEVELOPER_REPUTATION"),
  "08-INSURANCE": () => import("./lesson-08-INSURANCE"),
  "09-PREDICTION_MARKET": () => import("./lesson-09-PREDICTION_MARKET"),
  "09-FREELANCE_ESCROW": () => import("./lesson-09-FREELANCE_ESCROW"),
  "09-DAO": () => import("./lesson-09-DAO"),
  "09-DEVELOPER_REPUTATION": () => import("./lesson-09-DEVELOPER_REPUTATION"),
  "09-INSURANCE": () => import("./lesson-09-INSURANCE"),
  "10-PREDICTION_MARKET": () => import("./lesson-10-PREDICTION_MARKET"),
  "10-FREELANCE_ESCROW": () => import("./lesson-10-FREELANCE_ESCROW"),
  "10-DAO": () => import("./lesson-10-DAO"),
  "10-DEVELOPER_REPUTATION": () => import("./lesson-10-DEVELOPER_REPUTATION"),
  "10-INSURANCE": () => import("./lesson-10-INSURANCE"),
  "11-PREDICTION_MARKET": () => import("./lesson-11-PREDICTION_MARKET"),
  "11-FREELANCE_ESCROW": () => import("./lesson-11-FREELANCE_ESCROW"),
  "11-DAO": () => import("./lesson-11-DAO"),
  "11-DEVELOPER_REPUTATION": () => import("./lesson-11-DEVELOPER_REPUTATION"),
  "11-INSURANCE": () => import("./lesson-11-INSURANCE"),
  "12-PREDICTION_MARKET": () => import("./lesson-12-PREDICTION_MARKET"),
  "12-FREELANCE_ESCROW": () => import("./lesson-12-FREELANCE_ESCROW"),
  "12-DAO": () => import("./lesson-12-DAO"),
  "12-DEVELOPER_REPUTATION": () => import("./lesson-12-DEVELOPER_REPUTATION"),
  "12-INSURANCE": () => import("./lesson-12-INSURANCE"),
  "13-PREDICTION_MARKET": () => import("./lesson-13-PREDICTION_MARKET"),
  "13-FREELANCE_ESCROW": () => import("./lesson-13-FREELANCE_ESCROW"),
  "13-DAO": () => import("./lesson-13-DAO"),
  "13-DEVELOPER_REPUTATION": () => import("./lesson-13-DEVELOPER_REPUTATION"),
  "13-INSURANCE": () => import("./lesson-13-INSURANCE"),
  "14-PREDICTION_MARKET": () => import("./lesson-14-PREDICTION_MARKET"),
  "14-FREELANCE_ESCROW": () => import("./lesson-14-FREELANCE_ESCROW"),
  "14-DAO": () => import("./lesson-14-DAO"),
  "14-DEVELOPER_REPUTATION": () => import("./lesson-14-DEVELOPER_REPUTATION"),
  "14-INSURANCE": () => import("./lesson-14-INSURANCE"),
  "15-PREDICTION_MARKET": () => import("./lesson-15-PREDICTION_MARKET"),
  "15-FREELANCE_ESCROW": () => import("./lesson-15-FREELANCE_ESCROW"),
  "15-DAO": () => import("./lesson-15-DAO"),
  "15-DEVELOPER_REPUTATION": () => import("./lesson-15-DEVELOPER_REPUTATION"),
  "15-INSURANCE": () => import("./lesson-15-INSURANCE"),
  "16-PREDICTION_MARKET": () => import("./lesson-16-PREDICTION_MARKET"),
  "16-FREELANCE_ESCROW": () => import("./lesson-16-FREELANCE_ESCROW"),
  "16-DAO": () => import("./lesson-16-DAO"),
  "16-DEVELOPER_REPUTATION": () => import("./lesson-16-DEVELOPER_REPUTATION"),
  "16-INSURANCE": () => import("./lesson-16-INSURANCE"),
  "17-PREDICTION_MARKET": () => import("./lesson-17-PREDICTION_MARKET"),
  "17-FREELANCE_ESCROW": () => import("./lesson-17-FREELANCE_ESCROW"),
  "17-DAO": () => import("./lesson-17-DAO"),
  "17-DEVELOPER_REPUTATION": () => import("./lesson-17-DEVELOPER_REPUTATION"),
  "17-INSURANCE": () => import("./lesson-17-INSURANCE"),
  "18-PREDICTION_MARKET": () => import("./lesson-18-PREDICTION_MARKET"),
  "18-FREELANCE_ESCROW": () => import("./lesson-18-FREELANCE_ESCROW"),
  "18-DAO": () => import("./lesson-18-DAO"),
  "18-DEVELOPER_REPUTATION": () => import("./lesson-18-DEVELOPER_REPUTATION"),
  "18-INSURANCE": () => import("./lesson-18-INSURANCE"),
  "19-PREDICTION_MARKET": () => import("./lesson-19-PREDICTION_MARKET"),
  "19-FREELANCE_ESCROW": () => import("./lesson-19-FREELANCE_ESCROW"),
  "19-DAO": () => import("./lesson-19-DAO"),
  "19-DEVELOPER_REPUTATION": () => import("./lesson-19-DEVELOPER_REPUTATION"),
  "19-INSURANCE": () => import("./lesson-19-INSURANCE"),
  "20-PREDICTION_MARKET": () => import("./lesson-20-PREDICTION_MARKET"),
  "20-FREELANCE_ESCROW": () => import("./lesson-20-FREELANCE_ESCROW"),
  "20-DAO": () => import("./lesson-20-DAO"),
  "20-DEVELOPER_REPUTATION": () => import("./lesson-20-DEVELOPER_REPUTATION"),
  "20-INSURANCE": () => import("./lesson-20-INSURANCE"),
  "21-PREDICTION_MARKET": () => import("./lesson-21-PREDICTION_MARKET"),
  "21-FREELANCE_ESCROW": () => import("./lesson-21-FREELANCE_ESCROW"),
  "21-DAO": () => import("./lesson-21-DAO"),
  "21-DEVELOPER_REPUTATION": () => import("./lesson-21-DEVELOPER_REPUTATION"),
  "21-INSURANCE": () => import("./lesson-21-INSURANCE"),
  "22-PREDICTION_MARKET": () => import("./lesson-22-PREDICTION_MARKET"),
  "22-FREELANCE_ESCROW": () => import("./lesson-22-FREELANCE_ESCROW"),
  "22-DAO": () => import("./lesson-22-DAO"),
  "22-DEVELOPER_REPUTATION": () => import("./lesson-22-DEVELOPER_REPUTATION"),
  "22-INSURANCE": () => import("./lesson-22-INSURANCE"),
  "23-PREDICTION_MARKET": () => import("./lesson-23-PREDICTION_MARKET"),
  "23-FREELANCE_ESCROW": () => import("./lesson-23-FREELANCE_ESCROW"),
  "23-DAO": () => import("./lesson-23-DAO"),
  "23-DEVELOPER_REPUTATION": () => import("./lesson-23-DEVELOPER_REPUTATION"),
  "23-INSURANCE": () => import("./lesson-23-INSURANCE"),
  "24-PREDICTION_MARKET": () => import("./lesson-24-PREDICTION_MARKET"),
  "24-FREELANCE_ESCROW": () => import("./lesson-24-FREELANCE_ESCROW"),
  "24-DAO": () => import("./lesson-24-DAO"),
  "24-DEVELOPER_REPUTATION": () => import("./lesson-24-DEVELOPER_REPUTATION"),
  "24-INSURANCE": () => import("./lesson-24-INSURANCE"),
  "25-PREDICTION_MARKET": () => import("./lesson-25-PREDICTION_MARKET"),
  "25-FREELANCE_ESCROW": () => import("./lesson-25-FREELANCE_ESCROW"),
  "25-DAO": () => import("./lesson-25-DAO"),
  "25-DEVELOPER_REPUTATION": () => import("./lesson-25-DEVELOPER_REPUTATION"),
  "25-INSURANCE": () => import("./lesson-25-INSURANCE"),
  "26-PREDICTION_MARKET": () => import("./lesson-26-PREDICTION_MARKET"),
  "26-FREELANCE_ESCROW": () => import("./lesson-26-FREELANCE_ESCROW"),
  "26-DAO": () => import("./lesson-26-DAO"),
  "26-DEVELOPER_REPUTATION": () => import("./lesson-26-DEVELOPER_REPUTATION"),
  "26-INSURANCE": () => import("./lesson-26-INSURANCE"),
  "27-PREDICTION_MARKET": () => import("./lesson-27-PREDICTION_MARKET"),
  "27-FREELANCE_ESCROW": () => import("./lesson-27-FREELANCE_ESCROW"),
  "27-DAO": () => import("./lesson-27-DAO"),
  "27-DEVELOPER_REPUTATION": () => import("./lesson-27-DEVELOPER_REPUTATION"),
  "27-INSURANCE": () => import("./lesson-27-INSURANCE"),
  "28-PREDICTION_MARKET": () => import("./lesson-28-PREDICTION_MARKET"),
  "28-FREELANCE_ESCROW": () => import("./lesson-28-FREELANCE_ESCROW"),
  "28-DAO": () => import("./lesson-28-DAO"),
  "28-DEVELOPER_REPUTATION": () => import("./lesson-28-DEVELOPER_REPUTATION"),
  "28-INSURANCE": () => import("./lesson-28-INSURANCE"),
  "29-PREDICTION_MARKET": () => import("./lesson-29-PREDICTION_MARKET"),
  "29-FREELANCE_ESCROW": () => import("./lesson-29-FREELANCE_ESCROW"),
  "29-DAO": () => import("./lesson-29-DAO"),
  "29-DEVELOPER_REPUTATION": () => import("./lesson-29-DEVELOPER_REPUTATION"),
  "29-INSURANCE": () => import("./lesson-29-INSURANCE"),
  "30-PREDICTION_MARKET": () => import("./lesson-30-PREDICTION_MARKET"),
  "30-FREELANCE_ESCROW": () => import("./lesson-30-FREELANCE_ESCROW"),
  "30-DAO": () => import("./lesson-30-DAO"),
  "30-DEVELOPER_REPUTATION": () => import("./lesson-30-DEVELOPER_REPUTATION"),
  "30-INSURANCE": () => import("./lesson-30-INSURANCE"),
};

export async function getContent(
  lessonId: number,
  projectPath: ProjectPath
): Promise<LessonContent> {
  const key = `${String(lessonId).padStart(2, "0")}-${projectPath}`;
  const loader = contentMap[key];
  if (!loader) {
    throw new Error(
      `No content file found for lesson ${lessonId} / ${projectPath}. Create src/content/lessons/lesson-${String(lessonId).padStart(2, "0")}-${projectPath}.ts`
    );
  }
  const mod = await loader();
  return mod.default;
}
